version: '3.9'
services:
  postgresql-db:
    image: postgres:16-alpine
    container_name: postgresql-db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres_db